# Generated by Django 4.2.1 on 2023-05-20 12:40

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=jsonfield.fields.JSONField(),
        ),
    ]
