# Generated by Django 4.2.1 on 2023-05-20 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes_api', '0005_quiz_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='difficulty',
        ),
    ]
